### ISSUE TITLE
title discussion (for English, for now)

### ISSUE THREAD

**Issue by Mg138** [audreyt/edugame#1]
Scrolling through repos, this one ticked our interest.

「啟蒙導師」 seems like The definitive name for the game. Is the English equivalent going to stay as "edugame"?

Just for some nerding out time, we'd like to discuss the name in English, and potentially other languages (we only know English, though).

For starters, how does "ad intellectus" sound? "To the understanding" (as correct as our latin can get, correct us if we got Wikipedia's latin crashcourse wrong).

Not exactly English (just because we couldn't really find a good English title idea) but there've been English works with a Latin title (the obvious example is Ad Astra).

Or perhaps that's a little arcane sounding, maybe "Great(est) Mentors"?

Happy to hear y'all's thoughts :D

**Comment by bestian** [comment]
@Mg138 Thank you for your response and concern. This game was originally intended to be a tabletop card game. However, it was not successfully launched. The current data still retains some meaningful text and card files. If someone is interested in the future, perhaps it can be collaborated into a small game that runs on computers or mobile devices. As for the English name, I think your suggestion is very good.

**Comment by bestian** [comment]
Indeed, "Enlightened Tutor" is my original idea. This is because there was a Magic Card named "啟蒙導師" in Chinese, and its original name in English is "Enlightened Tutor".

**Comment by Mg138** [comment]
If we would be paid anything for it we'd be up to making something out of the ideas, or at least that we can say "we did X with this cool person can you hire me now :)" to employers.

Fun projects are fun, yeah, but we're kinda burned out on everything and constantly thinking about getting a job, which we've been trying to get one for 2 years.

We're basically just blatantly saying "hi hire us please" here, no pressure if you literally can't do that, but we need to put that out there.

Sorry for derailing, but we gotta generate some opportunities ourselves :/

**Comment by bestian** [comment]
> If we would be paid anything for it we'd be up to making something out of the ideas, or at least that we can say "we did X with this cool person can you hire me now :)" to employers.
> 
> Fun projects are fun, yeah, but we're kinda burned out on everything and constantly thinking about getting a job, which we've been trying to get one for 2 years.
> 
> We're basically just blatantly saying "hi hire us please" here, no pressure if you literally can't do that, but we need to put that out there.
> 
> Sorry for derailing, but we gotta generate some opportunities ourselves :/

It's okay, even if I can't hire you to improve this game right now, in old projects if there's any issues that can inspire, or any usable data, it's like finding sources of inspiration from a dusty cabinet.

Wishing you smooth sailing in your future endeavors.
